environment: dev

app:
  name: smart-energy-management
  debug: true

server:
  host: 0.0.0.0
  port: 8000

data_sources:
  flight_api_url: "MOCK"
  weather_api_url: "MOCK"
  iot_stream: "SIMULATED"
  energy_meter: "SIMULATED"

logging:
  level: INFO
  log_dir: logs/

feature_flags:
  enable_human_in_loop: true
  enable_simulation_mode: true
  enable_bms_control: false   # Phase-2
